add lighthouse

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -17,3 +17,7 @@ jobs:
         run: npm ci
       - name: Build Next.js app
         run: npm run build
+      - name: run Lighthouse CI
+        run: 
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
